platform :ios, '9.0'

#去掉pod警告
inhibit_all_warnings!
#use_frameworks!
target 'MDS' do
    #网络请求
    pod 'Alamofire', '~> 4.7.3'
    pod 'Moya'
    #json<--->model
    pod 'HandyJSON'
    #json
    pod 'SwiftyJSON'
    #HUD
    pod 'SVProgressHUD', '~> 2.2.5'
    #自动布局
    pod 'SnapKit', '~> 4.0.0'
    #上拉下拉刷新
    pod 'MJRefresh'
    #加载图片
    pod 'Kingfisher'
end
